spring:
  application:
    name: time-service
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka/}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics